
from topology import nodes as nodes
from topology import edges as edges

def getElem(entities, by, elem):
    for entity in entities:
        if getattr(entity, by) == elem:
            return entity
    return None

def exampleDate():
    attacker = nodes.template("attacker")
    victim = nodes.template("victim")
    router = nodes.template("router")
    vitsi = nodes.template("vitsi")

    local1 = nodes.l3network("local1", 24)
    local2 = nodes.l3network("local2", 24)
    backbone = nodes.l3network("backbone", 24)

    asgard = nodes.server("asgard", "asgard.net.in.tum.de")
    yggdrasil = nodes.server("yggdrasil", "yggdrasil.net.in.tum.de")

    attacker1 = nodes.device("attacker1")
    attacker2 = nodes.device("attacker2")
    attacker3 = nodes.device("attacker3")
    victim1 = nodes.device("victim1")
    bragi = nodes.device("bragi")
    hermod = nodes.device("hermod")
    bilskinir = nodes.device("bilskinir")
    folkwang = nodes.device("folkwang")

    attacker1AsAttacker = edges.deviceusestemplate(attacker1, attacker)
    attacker2AsAttacker = edges.deviceusestemplate(attacker2, attacker)
    attacker2AsAttacker = edges.deviceusestemplate(attacker3, attacker)
    victim1AsVictim = edges.deviceusestemplate(victim1, victim)
    bragiAsRouter = edges.deviceusestemplate(bragi, router)
    hermodAsRouter = edges.deviceusestemplate(hermod, router)
    bilskinirAsVitsi = edges.deviceusestemplate(bilskinir, vitsi)
    folkwangAsVitsi = edges.deviceusestemplate(folkwang, vitsi)

    attacker1OnAsgard = edges.devicerunsonserver(attacker1, asgard)
    attacker2OnAsgard = edges.devicerunsonserver(attacker2, asgard)
    bragiOnAsgard = edges.devicerunsonserver(bragi, asgard)
    bilskinirOnAsgard = edges.devicerunsonserver(bilskinir, asgard)
    victim1OnYggdrasil = edges.devicerunsonserver(victim1, yggdrasil)
    attacker3OnYggdrasil = edges.devicerunsonserver(attacker3, yggdrasil)
    hermodOnYggdrasil = edges.devicerunsonserver(hermod, yggdrasil)
    folkwangOnYggdrasil = edges.devicerunsonserver(folkwang, yggdrasil)

    bragi_eth0 = nodes.l2network("bragi_eth0")
    bragi_eth1 = nodes.l2network("bragi_eth1")
    hermod_eth0 = nodes.l2network("hermod_eth0")
    hermod_eth1 = nodes.l2network("hermod_eth1")
    bilskinir_eth0 = nodes.l2network("bilskinir_eth0")
    folkwang_eth0 = nodes.l2network("folkwang_eth0")
    victim_eth0 = nodes.l2network("victim_eth0")
    attacker1_eth0 = nodes.l2network("attacker1_eth0")
    attacker2_eth0 = nodes.l2network("attacker2_eth0")
    attacker3_eth0 = nodes.l2network("attacker3_eth0")

    bragi_mac1 = nodes.mac('00:11:22:33:44:55')
    bragi_mac2 = nodes.mac('01:11:22:33:44:55')
    hermod_mac1 = nodes.mac('11:11:22:33:44:55')
    hermod_mac2 = nodes.mac('10:11:22:33:44:55')
    bilskinir_mac1 = nodes.mac('31:11:22:33:44:55')
    folkwang_mac1 = nodes.mac('32:11:22:33:44:55')
    victim1_mac1 = nodes.mac('88:11:22:33:44:55')
    attacker1_mac1 = nodes.mac('91:11:22:33:44:55')
    attacker2_mac1 = nodes.mac('92:11:22:33:44:55')
    attacker3_mac1 = nodes.mac('93:11:22:33:44:55')

    bragi_iface1 = nodes.interface('bragi_iface1', 1)
    bragi_iface2 = nodes.interface('bragi_iface2', 2)
    hermod_iface1 = nodes.interface('hermod_iface1', 1)
    hermod_iface2 = nodes.interface('hermod_iface2', 2)
    bilskinir_iface1 = nodes.interface('31:11:22:33:44:55', 1)
    folkwang_iface1 = nodes.interface('folkwang_iface1', 1)
    victim1_iface1 = nodes.interface('victim1_iface1', 1)
    attacker1_iface1 = nodes.interface('attacker1_iface1', 1)
    attacker2_iface1 = nodes.interface('attacker2_iface1', 1)
    attacker3_iface1 = nodes.interface('attacker3_iface1', 1)

    bragimac1_has_iface1 = edges.mactointerface(bragi_mac1, bragi_iface1)
    bragi_mac2_has_iface2 = edges.mactointerface(bragi_mac2,bragi_iface2)
    hermod_mac1_has_iface1 = edges.mactointerface(hermod_mac1,hermod_iface1)
    hermod_mac2_has_iface2 = edges.mactointerface(hermod_mac2,hermod_iface2)
    bilskinir_mac1_has_iface1 = edges.mactointerface(bilskinir_mac1,bilskinir_iface1)
    folkwang_mac1_has_iface1 = edges.mactointerface(folkwang_mac1,folkwang_iface1)
    victim1_mac1_has_iface1 = edges.mactointerface(victim1_mac1,victim1_iface1)
    attacker1_mac1_has_iface1 = edges.mactointerface(attacker1_mac1,attacker1_iface1)
    attacker2_mac1_has_iface1 = edges.mactointerface(attacker2_mac1,attacker2_iface1)
    attacker3_mac1_has_iface1 = edges.mactointerface(attacker3_mac1,attacker3_iface1)

    bragi_mac1InEth0 = edges.interfaceisinnetwork(bragi_iface1, bragi_eth0)
    bragi_mac2InEth1 = edges.interfaceisinnetwork(bragi_iface2, bragi_eth1)
    hermod_mac1InEth0 = edges.interfaceisinnetwork(hermod_iface1, hermod_eth0)
    hermod_mac2InEth1 = edges.interfaceisinnetwork(hermod_iface2, hermod_eth1)
    bilskinir_mac1InEth0 = edges.interfaceisinnetwork(bilskinir_iface1,bilskinir_eth0)
    folkwang_mac1InEth0 = edges.interfaceisinnetwork(folkwang_iface1,folkwang_eth0)
    victim1_mac1InEth0 = edges.interfaceisinnetwork(victim1_iface1,victim_eth0)
    attacker1_mac1InEth0 = edges.interfaceisinnetwork(attacker1_iface1,attacker1_eth0)
    attacker2_mac1InEth0 = edges.interfaceisinnetwork(attacker2_iface1,attacker2_eth0)
    attacker3_mac1InEth0 = edges.interfaceisinnetwork(attacker3_iface1,attacker3_eth0)

    bragiHasInterfaceEth0 = edges.devicehasinterface(bragi,bragi_iface1)
    bragiHasInterfaceEth1 = edges.devicehasinterface(bragi,bragi_iface2)
    hermodHasInterfaceEth0 = edges.devicehasinterface(hermod,hermod_iface1)
    hermodHasInterfaceEth1 = edges.devicehasinterface(hermod,hermod_iface2)
    bilskinirHasInterfaceEth0 = edges.devicehasinterface(bilskinir,bilskinir_iface1)
    folkwangHasInterfaceEth0 = edges.devicehasinterface(folkwang,folkwang_iface1)
    victim1HasInterfaceEth0 = edges.devicehasinterface(victim1,victim1_iface1)
    attacker1HasInterfaceEth0 = edges.devicehasinterface(attacker1,attacker1_iface1)
    attacker2HasInterfaceEth0 = edges.devicehasinterface(attacker2,attacker2_iface1)
    attacker3HasInterfaceEth0 = edges.devicehasinterface(attacker3,attacker3_iface1)

    ip16_1 = nodes.ip('172.16.0.1')
    ip16_2 = nodes.ip('172.16.0.2')
    ip16_3 = nodes.ip('172.16.0.3')
    ip16_4 = nodes.ip('172.16.0.4')
    ip17_1 = nodes.ip('172.17.0.1')
    ip17_2 = nodes.ip('172.17.0.2')
    ip17_3 = nodes.ip('172.17.0.3')
    ip17_4 = nodes.ip('172.17.0.4')
    ip20_1 = nodes.ip('172.20.0.1')
    ip20_2 = nodes.ip('172.20.0.2')

    ip16_1_inLOC1 = edges.ipisinnetwork(ip16_1,local1)
    ip16_2_inLOC1 = edges.ipisinnetwork(ip16_2,local1)
    ip16_3_inLOC1 = edges.ipisinnetwork(ip16_3,local1)
    ip16_4_inLOC1 = edges.ipisinnetwork(ip16_4,local1)
    ip17_1_inLOC2 = edges.ipisinnetwork(ip17_1,local2)
    ip17_2_inLOC2 = edges.ipisinnetwork(ip17_2,local2)
    ip17_3_inLOC2 = edges.ipisinnetwork(ip17_3,local2)
    ip17_4_inLOC2 = edges.ipisinnetwork(ip17_4,local2)
    ip20_1_inBACK = edges.ipisinnetwork(ip20_1,backbone)
    ip20_2_inBACK = edges.ipisinnetwork(ip20_2,backbone)

    ip16_1_MAC = edges.iptomac(ip16_1,bragi_mac1)
    ip16_2_MAC = edges.iptomac(ip16_2,bilskinir_mac1)
    ip16_3_MAC = edges.iptomac(ip16_3,attacker1_mac1)
    ip16_4_MAC = edges.iptomac(ip16_4,attacker2_mac1)
    ip17_1_MAC = edges.iptomac(ip17_1,hermod_mac2)
    ip17_2_MAC = edges.iptomac(ip17_2,folkwang_mac1)
    ip17_3_MAC = edges.iptomac(ip17_3,attacker3_mac1)
    ip17_4_MAC = edges.iptomac(ip17_4,victim1_mac1)
    ip20_1_MAC = edges.iptomac(ip20_1,bragi_mac2)
    ip20_2_MAC = edges.iptomac(ip20_2,hermod_mac2) 


    #dos = nodes.attack('denial of service')
    #portScan = nodes.attack('port scan')
